logging:
  file: /tmp/logs/demo.log
#  level:
#    root: DEBUG
#    org.springframework: ERROR
#    com.spring.ibatis.UserMapper: DEBUG
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: demo
  http:
    encoding:
      force: true
  converters:
    preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true
  datasource:
    url: jdbc:mysql://172.16.9.15:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=false
    username: root
    password: a111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat,wall,log4j
    database: MySQL
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: select 1
      validation-query-timeout: 30
      test-while-idle: true
      keep-alive: true
      filters: stat,wall,log4j
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test-on-borrow: true
      test-on-return: false
      min-evictable-idle-time-millis: 3600000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 300000
      remove-abandoned: true #是否自动回收超时连接
      remove-abandoned-timeout: 180 #超时时间(以秒数为单位)
mybatis-plus:
  mapper-locations: com/**/mapper/xml/*Mapper.xml
  typeAliasesPackage: com.example.**
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false